#!/bin/bash

recording=$1

(
echo "set terminal png size 1000,600"
echo "set datafile separator \",\""
echo "set xlabel \"Minutes Elapsed\""
echo "set ylabel \"Memory\""
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M\""     # or anything else
echo "set title \"Connection estab, accept and fin\""
echo "plot \"$recording\" using 1:12 t \"FileNR\" w line"
) | gnuplot > ${recording}.png
