#!/bin/bash
#
# graph-appsvr-command <process-tcp> <process-command> <process-nginx> "title"
#
#   - process-tcp          time,date,SYN,SYNACK,FIN,RST
#   - process-command      time,date,incoming_device,incoming_wait,other,accu, 200,400
#   - process-nginx        time,date,counter,error,other
#
tcp_file=$1
command_file=$2
nginx_file=$3
title=$4

(
echo "set terminal png size 1200,1600"
echo "set multiplot layout 4,1"
echo "set datafile separator \",\""
echo "set xlabel \"Time Elapsed\""
# echo "set boxwidth 1.0"
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M\""     # or anything else
echo "set title \"$title\""
echo "set ylabel \"Network\""
echo "plot \"$tcp_file\" using 1:3 t \"SYN/s\" w boxes fill solid 1.0, \\"
echo "     '' using 1:4 t \"SYN-ACK/s\" w boxes fill solid 1.0, \\"
echo "     '' using 1:5 t \"FIN/s\" w boxes, \\"
echo "     '' using 1:6 t \"RST/s\" w boxes"
echo "set ylabel \"Application\""
echo "plot \"$command_file\" using 1:3 t \"Incoming\" w linespoint, \\"
echo "     '' using 1:7 t \"Served(200)\" w linespoint"
echo "set ylabel \"accumulated\""
echo "plot \"$command_file\"  using 1:(\$6 == 0 ? NaN : \$6) t \"clients\" w linespoint"
echo "set ylabel \"Nginx\""
echo "plot  \"$nginx_file\" using 1:3 t \"Nginx Counter\" w boxes fill solid 1.0, \\"
echo "     '' using 1:4 t \"Nginx Err/s\" w boxes fill solid 1.0"
#echo "set ylabel \"MB\""
#echo "plot \"$recording\"  using 1:(\$13 / 1024) t \"RSS\" w linespoint"
) | gnuplot > ${tcp_file}-complete.png
