#!/bin/bash
#
# graph-nginx <process-nginx>
#
#   - process-tcp          time,date,counter,error,other
#
traffic_file=$1

(
echo "set terminal png size 1000,600"
echo "set multiplot layout 2,1"
echo "set datafile separator \",\""
echo "set xlabel \"Time Elapsed\""
echo "set ylabel \"Events\""
# echo "set boxwidth 1.0"
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M\""     # or anything else
echo "set title \"Nginx connections\""
echo "plot \"$traffic_file\" using 1:3 t \"counter/s\" w boxes fill solid 1.0, \\"
echo "     '' using 1:4 t \"error/s\" w boxes fill solid 1.0, \\"
echo "     '' using 1:6 t \"other/s\" w boxes"
) | gnuplot > ${traffic_file}.png
