#!/bin/bash
#
# graph-qhist "title" <file>
#
#   - qhist          timestamp,ts,total,tot/s,...
#
title=$1
traffic_file=$2

(
echo "set terminal png size 1000,600"
echo "set multiplot layout 2,1"
echo "set datafile separator \",\""
echo "set xlabel \"Time Elapsed\""
echo "set ylabel \"Hits/s\""
# echo "set boxwidth 1.0"
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M:%S\""     # or anything else
echo "set title \"${title}\""
echo "plot \"$traffic_file\" using 1:5 t \"Total/s\" with linespoints\\"
echo "     ,'' using 1:4 t \"Total\" with linespoints\\"
) | gnuplot > ${traffic_file}.png
