#!/bin/bash
#
#   - process-command   time,date,incoming_device,incoming_wait,other,200,400
#
recording=$1

(
echo "set terminal png size 1000,600"
echo "set datafile separator \",\""
echo "set xlabel \"Minutes Elapsed\""
echo "set ylabel \"Clients\""
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M\""     # or anything else
echo "set title \"Connection estab, accept and fin\""
echo "plot \"$recording\" using 1:3 t \"incoming_devices\" w boxes fill solid 1.0, \\"
echo "     '' using 1:4 t \"incoming_wait\" w boxes fill solid 1.0, \\"
echo "     '' using 1:6 t \"200\" w boxes fill solid 1.0, \\"
echo "     '' using 1:7 t \"400\" w boxes fill solid 1.0"
) | gnuplot > ${recording}.png
