#!/bin/bash
#
#   - process-notification time,date,conn,disconn,decrypt_fail,other,accu,200,400,408
#
recording=$1

(
echo "set terminal png size 1600,600"
echo "set datafile separator \",\""
echo "set xlabel \"Minutes Elapsed\""
echo "set ylabel \"Clients\""
echo "set xdata time"
echo "set timefmt \"%s\""
echo "set format x \"%H:%M\""     # or anything else
echo "set title \"Connection estab, accept and fin\""
echo "plot \"$recording\" using 1:3 t \"Connections\" w boxes fill solid 1.0, \\"
echo "     '' using 1:4 t \"Disconnects\" w boxes fill solid 1.0"
) | gnuplot > ${recording}.png
