#!/usr/bin/perl -w
#
#1358614014.474113 IP 127.0.0.1.36656 > 127.0.0.1.14000: Flags [S], seq 1883124844, win 12288, options [mss 16396,nop,nop,sackOK,nop,wscale 10], length 0
#1358614014.474147 IP 127.0.0.1.14000 > 127.0.0.1.36656: Flags [S.], seq 2896662404, ack 1883124845, win 12288, options [mss 16396,nop,nop,sackOK,nop,wscale 10], length 0
#1358614014.474169 IP 127.0.0.1.36656 > 127.0.0.1.14000: Flags [.], ack 1, win 12, length 0
#1358614014.474261 IP 127.0.0.1.36656 > 127.0.0.1.14000: Flags [P.], seq 1:180, ack 1, win 12, length 179
#1358614014.474302 IP 127.0.0.1.14000 > 127.0.0.1.36656: Flags [.], ack 180, win 14, length 0
# turn into
#
# 127.0.0.1.36656 - 127.0.0.1.14000 [ SS., F.F., ., P. ]
#
# TS,         S, SA, F, FA
# 1358614010, 1, 1,  0, 0
# 1358614020, 1, 1,  0, 0
#
#  tcpdump -nn -tt -r file.pcap 'tcp[tcpflags] & #  (tcp-syn|tcp-fin) != 0' |  process-tcp > file.csv
use strict;

my %collapsed;
my $headerlines = 3;

sub remember_stack {
	my ($stack, $count) = @_;
	$collapsed{$stack} += $count;
}

my $nr = 0;
my @stack;

my $snap = 5 ;
my $last = 0;
my $count = 0;
my $total_count = 0;
my $unfinished = 0 ;
my %completed ;
my $min_time = 0;
my $max_time = 0;
my $time = 0;
my @flags = qw ( SYN SYN-ACK FIN );
my $flag ;
foreach (<>) {
    chomp ;

    ($time) = /^([\d\.]+)\s/ ;

    if ( /Flags \[([SFRP\.]+)\]/ ) {
        if ($1 eq 'S') {
            $flag = 'SYN';
        } elsif ($1 eq 'S.') {
            $flag = 'SYN-ACK';
        } elsif ($1 eq 'F.') {
            $flag = 'FIN';
        } else {
            next;
        }
    } else {
        die ("unexpected flag at $_");
    }

    # printf("debug: %d %s\n", $time, $flag);

    $time = int($time  / $snap) * $snap;

    if ($time > $max_time) {
        $max_time = $time;
    }
    if ($min_time == 0) {
        $min_time = $time;
    }
    $completed{$time}{$flag} ++  ;

=snip
    if ($time ne $last) {
        if ($last != 0) {
            printf("%d %d\n", $time, $count);

            $count = 1;

            $last = $time;
        } else {
            $last = $time;
            $count = 1;
        }
    } else {
        $count ++ ;
    }
=cut

}

printf("# parsed total %d syscalls, %d unfinished\n", $total_count, $unfinished);
printf("# time, date, %s\n", join(',',@flags));
for (my $idx = $min_time ; $idx < $max_time + $snap; $idx = $idx + $snap) {

    if (!exists($completed{$idx})) {
        printf("%s,%s,%s\n",
            $idx, scalar gmtime($idx),
            join(',', map { 0 } @flags));
        next;
    }

    printf("%d,%s", $idx, scalar gmtime($idx));
    foreach my $flag (@flags) {
        printf(",%d", $completed{$idx}{$flag} || 0);
    }
    printf("\n");

}
